/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internal;

import java.awt.Color;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Edit_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Edit_1
     */
    public Edit_1() {
        initComponents();
        setBounds(350,0,800,750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       public boolean action(String search,String stname, String fname, 
               String dob, String bform,String gender, String stmobile, 
               String fcnic, String fmobile, String program, int Package,
               int firstinstallment, int  matricrollno, String dateodadmission,
               int matricmarks, String admissionby, String approachedby, 
               String enteredby,String status )
{
        
        boolean flag=false;
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
           String sql = "Select * from student";
          PreparedStatement pst = conn.prepareStatement(sql);
          ResultSet rs=pst.executeQuery();
       
while(rs.next())
{  
        String BForm=rs.getString("BForm");
       if(BForm.equals(search))
           flag=true;
}
         }
         catch(Exception e)
         {
             
         }
        searchtf.setText(search);
        
        if(!flag)
        {
            return false;
        }
        if(flag)
        {
         StudentNametf.setText(stname);
     String stname_=StudentNametf.getText();
     
     FatherNametf.setText(fname);
        String fname_=FatherNametf.getText();
        
        DOB.setText(dob);
        String dob_=DOB.getText();
        
        BFormtf.setText(bform);
        String bform_=BFormtf.getText();
        
         boolean gen1=false;
         boolean gen2=false;

         if(gender.equals("Male"))
         {
             MaleCheck.setSelected(true);
             gen1=true;
         }
         else
         {
             FemaleCheck.setSelected(true);
             gen2=true;
         }
         
         StudentMobiletf.setText(stmobile);
        String stmobile_=StudentMobiletf.getText();
        
        FatherCNICtf.setText(fcnic);
        String fcnic_=FatherCNICtf.getText();
        
        FatherMobiletf.setText(fmobile);
        String fmobile_=FatherMobiletf.getText();
        
        Programtf.setText(program);
        String program_=Programtf.getText();
        
        Packagetf.setText(String.valueOf(Package));
        String _pac=Packagetf.getText();
         
        FirstInstallmenttf.setText(String.valueOf(firstinstallment));
        String FI=FirstInstallmenttf.getText();
        
           MatricRolltf.setText(String.valueOf(matricrollno));
        String MR=MatricRolltf.getText();
        
           AdmissionDatetf.setText(dateodadmission);
        String Ad=AdmissionDatetf.getText();
        
        
           MatricMarkstf.setText(String.valueOf(matricmarks));
        String MM=MatricMarkstf.getText();
        
           AdmissionBytf.setText(admissionby);
        String adby=AdmissionBytf.getText();
        
          ApproachedBytf.setText(approachedby);
        String APby=ApproachedBytf.getText();
          
           EnteredBytf.setText(enteredby);
        String enterby=EnteredBytf.getText();
            
        Statustf.setText(status);
        String status_=Statustf.getText();
           
     
         try {
                   Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
         String sql = "Update Student SET stname = ? ,FName=?,DOB=?, BForm = ?,gender=?, StMobile = ?  , "
                        + "FCNIC = ? , FMobile = ? , Program = ? , Package = ? , FirstInstallment = ?,"
                        + "MatricRoll = ? , DateOfAdmission= ? , MatricMarks = ?,"
                        + "AdmissionBy= ? , ApproachedBy = ? , EnteredBy = ?, Status=? WHERE BForm = '"+searchtf.getText()+"'";
                          
                PreparedStatement pr_st = con.prepareStatement(sql);
                
                pr_st.setString(1,StudentNametf.getText());
                pr_st.setString(2,FatherNametf.getText());
                
                pr_st.setString(3,DOB.getText());
                
                
                        pr_st.setString(4,BFormtf.getText());
                
                        if(MaleCheck.isSelected()==true)
                        {
                            pr_st.setString(5, "Male");
                        }
                        else if(FemaleCheck.isSelected()==true)
                        {
                            pr_st.setString(5, "Female");
                        }
                        
                        
                        pr_st.setString(6,StudentMobiletf.getText());
                
                        pr_st.setString(7,FatherCNICtf.getText());
                        
                        pr_st.setString(8,FatherMobiletf.getText());
                        
                        pr_st.setString(9,Programtf.getText());
                        
                        
                        pr_st.setString(10,Packagetf.getText());
                        
                        
                        pr_st.setString(11,FirstInstallmenttf.getText());
                        
                        
                        pr_st.setString(12,MatricRolltf.getText());
                        
                        pr_st.setString(13,AdmissionDatetf.getText());
                        
                        pr_st.setString(14,MatricMarkstf.getText());
                        
                        
                        pr_st.setString(15,AdmissionBytf.getText());
                        
                        pr_st.setString(16,ApproachedBytf.getText());
                        
                        
                        pr_st.setString(17,EnteredBytf.getText());
                        
                        
                        //pr_st.setString(17,EnteredBytf.getText());
                        
                        pr_st.setString(18,statustf.getText());
                        
                        
                int num = pr_st.executeUpdate();
           //     JOptionPane.showMessageDialog(null, num+"Record Updated");
        }
        
        catch (Exception ex) 
        {
            System.out.println(ex);
        }  
         return true;
        }
      
      return false;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StudentNametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FatherNametf = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        StudentMobiletf = new javax.swing.JTextField();
        FatherCNICtf = new javax.swing.JTextField();
        BFormtf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FatherMobiletf = new javax.swing.JTextField();
        Programtf = new javax.swing.JTextField();
        Packagetf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FirstInstallmenttf = new javax.swing.JTextField();
        MatricRolltf = new javax.swing.JTextField();
        MatricMarkstf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        AdmissionDatetf = new javax.swing.JTextField();
        AdmissionBytf = new javax.swing.JTextField();
        ApproachedBytf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        EnteredBytf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Statustf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        MaleCheck = new javax.swing.JRadioButton();
        FemaleCheck = new javax.swing.JRadioButton();
        Registerbtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();
        searchtf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        statustf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Edit Record");
        setOpaque(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        Jpanel.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Student Record");

        StudentNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNametfActionPerformed(evt);
            }
        });

        jLabel3.setText("Student Full Name");

        jLabel4.setText("FatherName");

        jLabel5.setText("DOB");

        FatherNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNametfActionPerformed(evt);
            }
        });

        DOB.setAlignmentX(0.0F);
        DOB.setMinimumSize(new java.awt.Dimension(64, 30));

        StudentMobiletf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentMobiletfActionPerformed(evt);
            }
        });

        FatherCNICtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherCNICtfActionPerformed(evt);
            }
        });

        BFormtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFormtfActionPerformed(evt);
            }
        });

        jLabel6.setText("BFormNo");

        jLabel7.setText("StudentMobile");

        jLabel8.setText("FatherCNIC");

        jLabel9.setText("FatherMobile");

        jLabel10.setText("Program");

        jLabel11.setText("Package");

        Packagetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PackagetfActionPerformed(evt);
            }
        });

        jLabel12.setText("First Installment");

        jLabel13.setText("Matric RollNo");

        jLabel14.setText("Matric Marks");

        jLabel15.setText("Admission Date");

        jLabel16.setText("Admission By");

        jLabel17.setText("Approached By");

        AdmissionBytf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmissionBytfActionPerformed(evt);
            }
        });

        jLabel18.setText("Entered By");

        jLabel19.setText("Status");

        jLabel20.setText("Gender");

        buttonGroup1.add(MaleCheck);
        MaleCheck.setText("Male");

        buttonGroup1.add(FemaleCheck);
        FemaleCheck.setText("Female");

        Registerbtn.setBackground(new java.awt.Color(44, 62, 80));
        Registerbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Update");
        Registerbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });

        Cancelbtn.setBackground(new java.awt.Color(44, 62, 80));
        Cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        Cancelbtn.setText("Cancel");
        Cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        searchtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchtfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchtfFocusLost(evt);
            }
        });
        searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtfActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(44, 62, 80));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setText("Status");

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FirstInstallmenttf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdmissionDatetf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FatherMobiletf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BFormtf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(StudentNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(67, 67, 67)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdmissionBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(MatricRolltf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(StudentMobiletf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(MatricMarkstf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApproachedBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(Statustf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(Programtf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addComponent(FatherNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20))
                                    .addComponent(MaleCheck))
                                .addGap(18, 18, 18)))
                        .addComponent(FemaleCheck)
                        .addGap(42, 42, 42)))
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnteredBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(FatherCNICtf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(Packagetf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statustf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(searchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel20))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FatherNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaleCheck)
                    .addComponent(FemaleCheck))
                .addGap(33, 33, 33)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FatherCNICtf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(StudentMobiletf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(BFormtf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Programtf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FatherMobiletf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Statustf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Packagetf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstInstallmenttf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatricRolltf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatricMarkstf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnteredBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdmissionDatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdmissionBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApproachedBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statustf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNametfActionPerformed

    private void FatherNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNametfActionPerformed

    private void StudentMobiletfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentMobiletfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentMobiletfActionPerformed

    private void FatherCNICtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherCNICtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherCNICtfActionPerformed

    private void BFormtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFormtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BFormtfActionPerformed

    private void PackagetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PackagetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PackagetfActionPerformed

    private void AdmissionBytfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmissionBytfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmissionBytfActionPerformed

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
        
        try {
                   Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
         String sql = "Update Student SET stname = ? ,FName=?,DOB=?, BForm = ?,gender=?, StMobile = ?  , "
                        + "FCNIC = ? , FMobile = ? , Program = ? , Package = ? , FirstInstallment = ?,"
                        + "MatricRoll = ? , DateOfAdmission = ? , MatricMarks = ?,"
                        + "AdmissionBy= ? , ApproachedBy = ? , EnteredBy = ?, Status=? WHERE BForm = '"+searchtf.getText()+"'";
                          
                PreparedStatement pr_st = con.prepareStatement(sql);
                
                pr_st.setString(1,StudentNametf.getText());
                pr_st.setString(2,FatherNametf.getText());
                
                pr_st.setString(3,DOB.getText());
                
                
                        pr_st.setString(4,BFormtf.getText());
                
                        if(MaleCheck.isSelected()==true)
                        {
                            pr_st.setString(5, "Male");
                        }
                        else if(FemaleCheck.isSelected()==true)
                        {
                            pr_st.setString(5, "Female");
                        }
                        
                        
                        pr_st.setString(6,StudentMobiletf.getText());
                
                        pr_st.setString(7,FatherCNICtf.getText());
                        
                        pr_st.setString(8,FatherMobiletf.getText());
                        
                        pr_st.setString(9,Programtf.getText());
                        
                        
                        pr_st.setString(10,Packagetf.getText());
                        
                        
                        pr_st.setString(11,FirstInstallmenttf.getText());
                        
                        
                        pr_st.setString(12,MatricRolltf.getText());
                        
                        pr_st.setString(13,AdmissionDatetf.getText());
                        
                        pr_st.setString(14,MatricMarkstf.getText());
                        
                        
                        pr_st.setString(15,AdmissionBytf.getText());
                        
                        pr_st.setString(16,ApproachedBytf.getText());
                        
                        
                        pr_st.setString(17,EnteredBytf.getText());
                        
                        
                        //pr_st.setString(17,EnteredBytf.getText());
                        
                        pr_st.setString(18,statustf.getText());
                        
                        
                int num = pr_st.executeUpdate();
                JOptionPane.showMessageDialog(null, num+"Record Updated");
        }
        catch (Exception ex) 
        {
            System.out.println(ex);
        }  
                
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void searchtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchtfFocusLost
        if(searchtf.getText().equals(""))
        {
            searchtf.setText("Enter Student BForm Number");
            searchtf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_searchtfFocusLost

    private void searchtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchtfFocusGained
        if(searchtf.getText().equals("Enter Student BForm Number"))
        {
            searchtf.setText("");
            searchtf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_searchtfFocusGained

    public void settext_search(String a)
    {
        searchtf.setText(a);
    }
   
     public void settext_Program(String a)
    {
        Programtf.setText(a);
    }
   
   
    public String test_Edit()
    {
        final String DB_URL = "jdbc:mysql://localhost:3306/Person?serverTimezone=UTC";
            final String USERNAME = "root";
            final String PASSWORD = "Muneeb@1372";
       
            String msg = null;
        Connection con;
        try {
            con = DriverManager.getConnection(DB_URL,USERNAME,PASSWORD);
            String sql_1 = "Select * from Student where BForm=?";    
                        PreparedStatement pr_st_1 = con.prepareStatement(sql_1);
                        pr_st_1.setString(1, searchtf.getText());
                        ResultSet rs_1 = pr_st_1.executeQuery();
                        rs_1.next();
                        String str = rs_1.getString("Program");
                        //System.out.println(str);
                        msg = str;
       
        } catch (SQLException ex) {
            Logger.getLogger(Edit_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return msg;
    }
   
    public String Action_Search()
    {
       
        String msg = null;
        final String DB_URL = "jdbc:mysql://localhost:3306/Person?serverTimezone=UTC";
            final String USERNAME = "root";
            final String PASSWORD = "Muneeb@1372";
        try {
                Connection con = DriverManager.getConnection(DB_URL,USERNAME,PASSWORD);
                String sql = "Select * from Student";    
                PreparedStatement pr_st = con.prepareStatement(sql);
                //pr_st.setString(1, jTextField1.getText());
                ResultSet rs = pr_st.executeQuery();
                boolean a =false;
                String q = searchtf.getText();
                while(rs.next())
                {
                    if(searchtf.getText().equals(rs.getString("BForm")))
                        a = true;
                }
                if(a==true)
                {
                        String sql_1 = "Select * from Student where BForm=?";    
                        PreparedStatement pr_st_1 = con.prepareStatement(sql_1);
                        pr_st_1.setString(1, searchtf.getText());
                        ResultSet rs_1 = pr_st_1.executeQuery();
                        rs_1.next();
                        String str = rs_1.getString("stname");
                    String str_1 = rs_1.getString("FatherName");
                    String str_2 = rs_1.getString("DOB");
                    String str_3 = rs_1.getString("BForm");
                    String str_4 = rs_1.getString("gender");
                    String str_5 = rs_1.getString("StMobile");
                    String str_6 = rs_1.getString("FCNIC");
                    String str_7 = rs_1.getString("FMobile");
                    String str_8 = rs_1.getString("Program");
                    String str_9 = rs_1.getString("Package");
                    String str_10 = rs_1.getString("FirstInstallment");
                    String str_11 = rs_1.getString("MatricRoll");
                    String str_12 = rs_1.getString("DateOfAdmission");
                    String str_13 = rs_1.getString("MatricMarks");
                    String str_14 = rs_1.getString("AdmissionBy");
                    String str_15 = rs_1.getString("ApproachedBy");
                    String str_16 =  rs_1.getString("EnteredBy");
                    //                 rs.getString("Status");
                   
                    msg = str_8;
                    JOptionPane.showMessageDialog(null, "Successfull Search Query");
                   
                    StudentNametf.setText(str);
                    FatherNametf.setText(str_1);
                    DOB.setText(str_2);  
                    BFormtf.setText(str_3);
                    StudentMobiletf.setText(str_5);
                    FatherCNICtf.setText(str_6);
                    FatherMobiletf.setText(str_7);
                    Programtf.setText(str_8);
                    Packagetf.setText(str_9);
                    FirstInstallmenttf.setText(str_10);
                    MatricRolltf.setText(str_11);
                    AdmissionDatetf.setText(str_12);
                    MatricMarkstf.setText(str_13);
                    AdmissionBytf.setText(str_14);
                    ApproachedBytf.setText(str_15);
                    EnteredBytf.setText(str_16);
                   
                }else
                {
                    JOptionPane.showMessageDialog(null, "Please enter valid BForm Number");
                    msg = "Please enter valid BForm Number";
                }  
        }catch (SQLException ex) {
            Logger.getLogger(Edit_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return msg;
    }

    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        try {
              Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
        String sql = "Select * from student";    
                PreparedStatement pr_st = con.prepareStatement(sql);
                //pr_st.setString(1, jTextField1.getText());
                ResultSet rs = pr_st.executeQuery();
                boolean a =false;
                String q = searchtf.getText();
                while(rs.next())
                {
                    if(searchtf.getText().equals(rs.getString("BForm")))
                        a = true;
                }
                if(a==true)
                {
                        String sql_1 = "Select * from student where BForm=?";    
                        PreparedStatement pr_st_1 = con.prepareStatement(sql_1);
                        pr_st_1.setString(1, searchtf.getText());
                        ResultSet rs_1 = pr_st_1.executeQuery();
                        rs_1.next();
                        String str = rs_1.getString("stname");
                    String str_1 = rs_1.getString("FName");
                    String str_2 = rs_1.getString("DOB");
                    String str_3 = rs_1.getString("BForm");
                    String str_4 = rs_1.getString("gender");
                    
                    if(str_4.equals("Male"))
                    {
                        MaleCheck.setSelected(true);
                    }
                    else{
                        FemaleCheck.setSelected(true);
                    }
                    String str_5 = rs_1.getString("StMobile");
                    String str_6 = rs_1.getString("FCNIC");
                    String str_7 = rs_1.getString("FMobile");
                    String str_8 = rs_1.getString("Program");
                    String str_9 = rs_1.getString("Package");
                    String str_10 = rs_1.getString("FirstInstallment");
                    String str_11 = rs_1.getString("MatricRoll");
                    String str_12 = rs_1.getString("DateOfAdmission");
                    String str_13 = rs_1.getString("MatricMarks");
                    String str_14 = rs_1.getString("AdmissionBy");
                    String str_15 = rs_1.getString("ApproachedBy");
                    String str_16 =  rs_1.getString("EnteredBy");
                     String str_17 =  rs_1.getString("Status");
                    //                 rs.getString("Status");
                    StudentNametf.setText(str);
                    FatherNametf.setText(str_1);
                    DOB.setText(str_2);  
                    BFormtf.setText(str_3);
                    StudentMobiletf.setText(str_5);
                    FatherCNICtf.setText(str_6);
                    FatherMobiletf.setText(str_7);
                    Programtf.setText(str_8);
                    Packagetf.setText(str_9);
                    FirstInstallmenttf.setText(str_10);
                    MatricRolltf.setText(str_11);
                    AdmissionDatetf.setText(str_12);
                    MatricMarkstf.setText(str_13);
                    AdmissionBytf.setText(str_14);
                    ApproachedBytf.setText(str_15);
                    EnteredBytf.setText(str_16);
                    statustf.setText(str_17);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Please enter valid BForm Number");
                }  
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        } 
            
            
            
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtfActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AdmissionBytf;
    public javax.swing.JTextField AdmissionDatetf;
    public javax.swing.JTextField ApproachedBytf;
    public javax.swing.JTextField BFormtf;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JTextField DOB;
    public javax.swing.JTextField EnteredBytf;
    public javax.swing.JTextField FatherCNICtf;
    public javax.swing.JTextField FatherMobiletf;
    private javax.swing.JTextField FatherNametf;
    private javax.swing.JRadioButton FemaleCheck;
    public javax.swing.JTextField FirstInstallmenttf;
    private javax.swing.JPanel Jpanel;
    private javax.swing.JRadioButton MaleCheck;
    public javax.swing.JTextField MatricMarkstf;
    public javax.swing.JTextField MatricRolltf;
    public javax.swing.JTextField Packagetf;
    public javax.swing.JTextField Programtf;
    private javax.swing.JButton Registerbtn;
    public javax.swing.JTextField Statustf;
    public javax.swing.JTextField StudentMobiletf;
    public javax.swing.JTextField StudentNametf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField searchtf;
    public javax.swing.JTextField statustf;
    // End of variables declaration//GEN-END:variables
}
