/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import scdproject_2.OfficeBoyLogin;

/**
 *
 * @author Hassan
 */
public class Frame9_AccountCreation extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frame9_AccountCreation
     */
    public Frame9_AccountCreation() {
        initComponents();
        setBounds(350,0,700,700);
    }

    
    public boolean action(String uname,String pass)
    {
                nametf.setText(uname);
                passwordtf.setText(pass);
        
         String name=nametf.getText();
                String password=passwordtf.getText();
                
                try{
                     Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
    
            String sql = "INSERT INTO loginuser (username,password)" +
                         "VALUES(?,?)";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
          
            preparedStatement.setString(1, name);
            preparedStatement.setString(2, password);
            
            
            int addrows = preparedStatement.executeUpdate();
            
                    conn.close();
                    if(addrows!=0)
            return true;
                    
                }
        
                catch(Exception e)
                {
                    
                }
                return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupbtn = new javax.swing.JButton();
        namelabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        passwordtf = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Office Boy Account Creation");
        setOpaque(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        signupbtn.setBackground(new java.awt.Color(44, 62, 80));
        signupbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signupbtn.setText("Sign Up");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });

        namelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namelabel.setText("Name");

        jPanel1.setBackground(new java.awt.Color(51, 77, 92));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Sign Up here");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hassan\\Downloads\\SCD_Project\\SCD_Project\\src\\scd_project\\icons8-manager-80.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        passwordlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordlabel.setText("Password");

        nametf.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N

        passwordtf.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordtf, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(nametf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(namelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
          String name=nametf.getText();
                String password=passwordtf.getText();
                
                try{
                     Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
    
            String sql = "INSERT INTO loginuser (username,password)" +
                         "VALUES(?,?)";
             String sql_ = "select * from loginuser ";
            
            PreparedStatement preparedStatement_ = conn.prepareStatement(sql_);
                    ResultSet rs=preparedStatement_.executeQuery();
                    
                    while(rs.next())
                    {
                
                       String namem= rs.getString(1);
                        
                        if(rs.getString(1).equals(name))
                        {
                            JOptionPane.showMessageDialog(this,"Already used username.");
                            
                        }
                    }
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
          
            preparedStatement.setString(1, name);
            preparedStatement.setString(2, password);

            int addrows = preparedStatement.executeUpdate();
            
            
            JOptionPane.showMessageDialog(Frame9_AccountCreation.this,
                            "Successfully Created Account","Success",
                            JOptionPane.ERROR_MESSAGE);
            conn.close();
            
            
                }
        
                catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_signupbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTextField passwordtf;
    private javax.swing.JButton signupbtn;
    // End of variables declaration//GEN-END:variables
}
