/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;  
import org.jfree.data.general.DefaultPieDataset;
//import javafx.collections.FXCollections;

/**
 *
 * @author Hassan
 */
public class Frame7_totalInstallment extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frame7_totalInstallment
     */
    public Frame7_totalInstallment() {
        initComponents();
        showInstallment();
        setBounds(350,0,700,700);
    }
    public boolean action()
    {
        if(!jLabel11.getText().equals(""))
            return true;
        
        return false;
    }
    
    public void showInstallment()
    {
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
           String sql = "Select * from student";
          PreparedStatement pst = conn.prepareStatement(sql);
          ResultSet rs=pst.executeQuery();
          int sum=0;
          while(rs.next())
          {
              sum=sum+rs.getInt("FirstInstallment");
              
          }
        //  String str=Integer.parseInt(sum);
        
         String res3 = String.valueOf(sum);
          jLabel11.setText(res3);
          
          conn.close();
         }
         
         
         
         catch(Exception e)
         {
             e.printStackTrace();
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Barbtn = new javax.swing.JButton();
        Piebtn = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        jToolBar1.setRollover(true);

        setClosable(true);
        setTitle("Total Installment");
        setOpaque(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hassan\\Downloads\\installment turkey.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Total Installment");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Total Installments:");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Barbtn.setBackground(new java.awt.Color(44, 62, 80));
        Barbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Barbtn.setForeground(new java.awt.Color(255, 255, 255));
        Barbtn.setText("Bar Chart");
        Barbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Barbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarbtnActionPerformed(evt);
            }
        });

        Piebtn.setBackground(new java.awt.Color(44, 62, 80));
        Piebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Piebtn.setForeground(new java.awt.Color(255, 255, 255));
        Piebtn.setText("Pie Chart");
        Piebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Piebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Barbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(Piebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Barbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Piebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarbtnActionPerformed
        // TODO add your handling code here:
        //String date="";
        int sum1=0;
          int sum2=0;
          int sum3=0;
          String str1="%2021";
          String str2="%2020";
          String str3="%2019";
           try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
           String sql = "Select * from student where DateOfAdmission like '"+str1+"'";
          PreparedStatement pst = conn.prepareStatement(sql);
          ResultSet rs=pst.executeQuery();
          
          while(rs.next())
          {
              sum1=sum1+rs.getInt("FirstInstallment");
              
          }
//           System.out.println(sum1);

           String sql2 = "Select * from student where DateOfAdmission like '"+str2+"'";
          pst = conn.prepareStatement(sql2);
          rs=pst.executeQuery();
           while(rs.next())
          {
              sum2=sum2+rs.getInt("FirstInstallment");
              
          }
//            System.out.println(sum2);
            String sql3 = "Select * from student where DateOfAdmission like '"+str3+"'";
          pst = conn.prepareStatement(sql3);
          rs=pst.executeQuery();
           while(rs.next())
          {
              sum3=sum3+rs.getInt("FirstInstallment");
          }
           
//               System.out.println(sum3);
       
          conn.close();
         }
         
         
         
         catch(Exception e)
         {
             e.printStackTrace();
         }
        
        
        
        
        DefaultCategoryDataset ds=new DefaultCategoryDataset();
        ds.setValue(sum1,"Years","2021");        
      ds.setValue(sum2,"Years","2020");        
      ds.setValue(sum3,"Years","2019");        
     
      JFreeChart chart=ChartFactory.createBarChart("Graph For 3 Years","Years","Total Installments(Rs)",ds,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLACK);
        ChartFrame frame=new  ChartFrame("Bar Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
        
        

        
        
    }//GEN-LAST:event_BarbtnActionPerformed

    private void PiebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiebtnActionPerformed
        // TODO add your handling code here
   int sum1=0;
          int sum2=0;
          int sum3=0;
          String str1="%2021";
          String str2="%2020";
          String str3="%2019";
           try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/user?useSSL=false", "root", "ahmad1122");
           String sql = "Select * from student where DateOfAdmission like '"+str1+"'";
          PreparedStatement pst = conn.prepareStatement(sql);
          ResultSet rs=pst.executeQuery();
          
          while(rs.next())
          {
              sum1=sum1+rs.getInt("FirstInstallment");
              
          }
//           System.out.println(sum1);

           String sql2 = "Select * from student where DateOfAdmission like '"+str2+"'";
          pst = conn.prepareStatement(sql2);
          rs=pst.executeQuery();
           while(rs.next())
          {
              sum2=sum2+rs.getInt("FirstInstallment");
              
          }
//            System.out.println(sum2);
            String sql3 = "Select * from student where DateOfAdmission like '"+str3+"'";
          pst = conn.prepareStatement(sql3);
          rs=pst.executeQuery();
           while(rs.next())
          {
              sum3=sum3+rs.getInt("FirstInstallment");
          }
           
//               System.out.println(sum3);
       
          conn.close();
         }
         
         
         
         catch(Exception e)
         {
             e.printStackTrace();
         }
           
        DefaultPieDataset ds=new DefaultPieDataset();
        ds.setValue("2021",sum1);        
      ds.setValue("2020",sum2);        
      ds.setValue("2019",sum3);        
     
      JFreeChart chart=ChartFactory.createPieChart3D("3 Years Installment",ds,true,true,true);
        PiePlot3D p=(PiePlot3D)chart.getPlot();
      
      ChartFrame frame=new  ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,500);

        
        
        
    }//GEN-LAST:event_PiebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Barbtn;
    private javax.swing.JButton Piebtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
