/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scdproject_2;

import internal.Frame10_DeleteOfficeBoyAccount;
import internal.Frame1_viewstd;
import internal.Frame2_addStudent;
import internal.Frame8_SeperateGender;
import internal.Frame9_AccountCreation;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author Hassan
 */
public class Mainpanel_Admin extends javax.swing.JFrame {
    Frame1_viewstd frm1;   
    Frame9_AccountCreation frm2;   
    Frame10_DeleteOfficeBoyAccount frm3;
    
 
    public Mainpanel_Admin() {
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Main Panel");
    
        setResizable(true);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public boolean Action3(int no)
    {
          if(frm3!=null)
           frm3.dispose();
        
        if(frm3==null||frm3.isClosed())
        {
                frm3=new  Frame10_DeleteOfficeBoyAccount();      
               this.jPanel1.add(frm3,BorderLayout.CENTER);
                 frm3.setVisible(true); 
        }
        return frm3.action(no);
    }
    public boolean Action(String uname,String pas)
    {
          if(frm2!=null)
           frm2.dispose();
        
        if(frm2==null||frm2.isClosed())
        {
                frm2=new  Frame9_AccountCreation();      
               this.jPanel1.add(frm2,BorderLayout.CENTER);
                 frm2.setVisible(true); 
        }
        return frm2.action(uname,pas);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        PortalLabel = new javax.swing.JLabel();
        createAccbtn = new javax.swing.JButton();
        deleteaccbtn = new javax.swing.JButton();
        ViewStudentbtn1 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        PortalLabel.setBackground(new java.awt.Color(204, 204, 255));
        PortalLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        PortalLabel.setForeground(new java.awt.Color(51, 51, 51));
        PortalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PortalLabel.setText("Welcome to Admin Portal ");
        PortalLabel.setAlignmentX(0.9F);
        PortalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PortalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        createAccbtn.setBackground(new java.awt.Color(44, 62, 80));
        createAccbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createAccbtn.setForeground(new java.awt.Color(255, 255, 255));
        createAccbtn.setText("Create OfficeBoy Account");
        createAccbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccbtnActionPerformed(evt);
            }
        });

        deleteaccbtn.setBackground(new java.awt.Color(44, 62, 80));
        deleteaccbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteaccbtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteaccbtn.setText("Delete OfficeBoy Account");
        deleteaccbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteaccbtnActionPerformed(evt);
            }
        });

        ViewStudentbtn1.setBackground(new java.awt.Color(44, 62, 80));
        ViewStudentbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewStudentbtn1.setForeground(new java.awt.Color(255, 255, 255));
        ViewStudentbtn1.setText("View All Students");
        ViewStudentbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewStudentbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PortalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewStudentbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PortalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewStudentbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(deleteaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccbtnActionPerformed
        if(frm2!=null)
        frm2.dispose();

        if(frm2==null||frm2.isClosed()){
            frm2=new Frame9_AccountCreation();

            jPanel1.add(frm2,BorderLayout.CENTER);
            frm2.setVisible(true);

            //                AddStudent addStudent=new AddStudent();
        }
        else
        {
            //           frm.setVisible(true);
        }

    }//GEN-LAST:event_createAccbtnActionPerformed

    private void deleteaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteaccbtnActionPerformed

           if(frm3!=null)
        frm3.dispose();

        if(frm3==null||frm3.isClosed()){
            frm3=new Frame10_DeleteOfficeBoyAccount();

            jPanel1.add(frm3,BorderLayout.CENTER);
            frm3.setVisible(true);

            //                AddStudent addStudent=new AddStudent();
        }
        else
        {
            //           frm.setVisible(true);
        }
    }//GEN-LAST:event_deleteaccbtnActionPerformed

    private void ViewStudentbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentbtn1ActionPerformed
        // TODO add your handling code here:
         if(frm1!=null)
           frm1.dispose();
        
        if(frm1==null||frm1.isClosed()){
                frm1=new Frame1_viewstd();
              
                jPanel1.add(frm1,BorderLayout.CENTER);
                frm1.setVisible(true);
           
//                AddStudent addStudent=new AddStudent();
        }
    }//GEN-LAST:event_ViewStudentbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpanel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpanel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpanel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpanel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpanel_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PortalLabel;
    private javax.swing.JButton ViewStudentbtn1;
    private javax.swing.JButton createAccbtn;
    private javax.swing.JButton deleteaccbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
